### ISSUE TITLE
Android端build.gradle错误

### ISSUE THREAD

**Issue by ohyes666** [seasonZhu/GetXStudy#1]
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.getx_study"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion 19
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

```

把android/app/build.gradle中内容改一下 就可以编译了。你把上面内容复制进去就可以了。

**Comment by ohyes666** [comment]
Android 编译之后运行。在debug模式下 报错
I/flutter ( 8615): Could not start Dart VM service HTTP server:
I/flutter ( 8615): SocketException: Failed to create server socket (OS Error: Permission denied, errno = 13), address = 127.0.0.1, port = 0
I/flutter ( 8615): #0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:996:7)
I/flutter ( 8615): <asynchronous suspension>
I/flutter ( 8615): #1      Server.startup.startServer (dart:vmservice_io/vmservice_server.dart:414:19)
I/flutter ( 8615): <asynchronous suspension>
I/flutter ( 8615): #2      Server.startup (dart:vmservice_io/vmservice_server.dart:433:11)
I/flutter ( 8615): <asynchronous suspension>

**Comment by seasonZhu** [comment]
不好意思，最近项目忙，没太注意看这个项目的issue，谢谢，我是安卓小白，谢谢指导！
